In [81]:
import pandas as pd 
import json

In [82]:
with open('../election-stations-2569.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# หาหน่วยเลือกตั้งของจังหวัด
rayong = next((p for p in data['provinces'] if p['name'] == 'ระยอง'), None)
# print(f"ระยอง {rayong['total_stations']} หน่วยเลือกตั้ง")
d = dict()
t = 0
# หาหน่วยเลือกตั้งจากรหัส
def find_total_station(area,province):
    for p in data['provinces']:
        if p['name'] == province:
            for a in p['areas']:
                if a['area'] == area:
                    for unit in a['stations']:
                        if unit['district'] not in d:
                            d[unit['district']] = dict()
                        if unit['subdistrict'] not in  d[unit['district']]:
                            d[unit['district']][unit['subdistrict']] = 1
                        else:
                            d[unit['district']][unit['subdistrict']] += 1
    return None

find_total_station(2, 'ลำปาง')
print(d)
for k, v in d.items():
    for e, g in v.items():
        t+=g
print(t)

{'เมืองลำปาง': {'บ้านแลง': 12, 'บ้านเสด็จ': 19}, 'งาว': {'หลวงเหนือ': 7, 'หลวงใต้': 8, 'บ้านโป่ง': 12, 'บ้านร้อง': 13, 'ปงเตา': 13, 'นาแก': 6, 'บ้านอ้อน': 8, 'บ้านแหง': 9, 'บ้านหวด': 7, 'แม่ตีบ': 7}, 'แจ้ห่ม': {'แจ้ห่ม': 14, 'บ้านสา': 10, 'ปงดอน': 9, 'แม่สุก': 12, 'เมืองมาย': 7, 'ทุ่งผึ้ง': 8, 'วิเชตนคร': 12}, 'วังเหนือ': {'ทุ่งฮั้ว': 12, 'วังเหนือ': 12, 'วังใต้': 7, 'ร่องเคาะ': 18, 'วังทอง': 9, 'วังซ้าย': 10, 'วังแก้ว': 7, 'วังทรายคำ': 9}, 'เมืองปาน': {'เมืองปาน': 11, 'บ้านขอ': 14, 'ทุ่งกว๋าว': 16, 'แจ้ซ้อน': 15, 'หัวเมือง': 9}}
342

In [83]:
all_distrcit = []
all_subdistrict = []
district_count = {}
for k,v in d.items():
    all_distrcit.append(k)
    all_subdistrict += v.keys()
    for key in v.keys():
        if k not in district_count:
            district_count[k] = v[key]
        else: district_count[k]+= v[key]

In [84]:
district_count

{'เมืองลำปาง': 31, 'งาว': 90, 'แจ้ห่ม': 72, 'วังเหนือ': 84, 'เมืองปาน': 65}

In [85]:
summary = pd.read_csv("../master_summary.csv")
summary.head(5)

,type,province,district,sub-district,unit_number,total_ballots,valid_ballots,invalid_ballots,no_vote_ballots,remain_ballots
0,บช,ลำปาง,นอกเขต,ชุดที่ 1,-1,700,663,8,29,-1
1,เขต,ลำปาง,นอกเขต,ชุดที่ 1,-1,700,605,32,63,-1
2,บช,ลำปาง,นอกเขต,ชุดที่ 10,-1,700,668,8,24,-1
3,เขต,ลำปาง,นอกเขต,ชุดที่ 10,-1,700,616,28,56,-1
4,บช,ลำปาง,นอกเขต,ชุดที่ 11,-1,700,664,6,30,-1

In [86]:
results = pd.read_csv("../master_results.csv")
results.head(5)

  type province district sub-district  unit_number          name score
0   บช    ลำปาง   นอกเขต     ชุดที่ 1           -1  ไทยทรัพย์ทวี     0
1   บช    ลำปาง   นอกเขต     ชุดที่ 1           -1  เพื่อชาติไทย     6
2   บช    ลำปาง   นอกเขต     ชุดที่ 1           -1          ใหม่     4
3   บช    ลำปาง   นอกเขต     ชุดที่ 1           -1      มิติใหม่     0
4   บช    ลำปาง   นอกเขต     ชุดที่ 1           -1      รวมใจไทย     1

In [87]:
summary.info()

<class 'pandas.DataFrame'>
RangeIndex: 710 entries, 0 to 709
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   type             710 non-null    str
 1   province         710 non-null    str
 2   district         710 non-null    str
 3   sub-district     710 non-null    str
 4   unit_number      710 non-null    int64
 5   total_ballots    710 non-null    int64
 6   valid_ballots    710 non-null    int64
 7   invalid_ballots  710 non-null    int64
 8   no_vote_ballots  710 non-null    int64
 9   remain_ballots   710 non-null    int64
dtypes: int64(6), str(4)
memory usage: 55.6 KB

In [88]:
for col in summary.columns:
    if summary[(summary[col] == '-1') | (summary[col] == -1)][col].sum():
        print(f"with column: {col} have -1 total be: {summary[(summary[col] == '-1') | (summary[col] == -1)][col].sum()}")

with column: unit_number have -1 total be: -26
with column: total_ballots have -1 total be: -2
with column: invalid_ballots have -1 total be: -7
with column: no_vote_ballots have -1 total be: -11
with column: remain_ballots have -1 total be: -164

In [89]:
fix_district={
}
for district in all_distrcit:
    df_district = summary[summary['district'].str.contains(district)]['district']
    if len(df_district)/2 != district_count[district]:
        print(f"District: {district} have total unit: {len(df_district)} but target is: {district_count[district]}")
    for miss_district in df_district.unique():
        if miss_district!= district:
            fix_district[miss_district] = district

District: งาว have total unit: 176 but target is: 90

In [90]:
for miss_district, real in fix_district.items():
    summary.loc[summary['district'] == miss_district, 'district'] = real
for district in all_distrcit:
    print(summary[summary['district'].str.contains(district)]['district'].unique())

<StringArray>
['เมืองลำปาง']
Length: 1, dtype: str
<StringArray>
['งาว']
Length: 1, dtype: str
<StringArray>
['แจ้ห่ม']
Length: 1, dtype: str
<StringArray>
['วังเหนือ']
Length: 1, dtype: str
<StringArray>
['เมืองปาน']
Length: 1, dtype: str

In [91]:
# fix sub-district
counts = summary['sub-district'].value_counts()

result = counts[counts == 1].index.tolist()
summary[summary['sub-district'].isin(result)]

,type,province,district,sub-district,unit_number,total_ballots,valid_ballots,invalid_ballots,no_vote_ballots,remain_ballots
418,เขต,ลำปาง,เมืองปาน,เจริญยุทธ,10,120,66,5,1,43
422,เขต,ลำปาง,เมืองปาน,เจ้าซ้อน,14,320,217,11,1,91
427,เขต,ลำปาง,เมืองปาน,แจ้งขึ้น,5,460,313,24,12,111
430,เขต,ลำปาง,เมืองปาน,เจ็ดสิบ,8,600,375,24,11,-1
439,บช,ลำปาง,เมืองปาน,ทุ่งกว้าง,16,800,180,25,11,-1

In [92]:
c = summary[summary['district'] == 'เมืองปาน']['sub-district'].value_counts().index.tolist()
c

['ทุ่งกว๋าว',
 'บ้านขอ',
 'เมืองปาน',
 'หัวเมือง',
 'แจ้ซ้อน',
 'เจ้ซ้อน',
 'เจริญยุทธ',
 'เจ้าซ้อน',
 'แจ้งขึ้น',
 'เจ็ดสิบ',
 'ทุ่งกว้าง']

In [93]:
c[5:-1]

['เจ้ซ้อน', 'เจริญยุทธ', 'เจ้าซ้อน', 'แจ้งขึ้น', 'เจ็ดสิบ']

In [94]:
summary.loc[summary['sub-district'].isin(c[5:-1]), 'sub-district'] = c[4]
summary.loc[summary['sub-district'].isin([c[-1]]), 'sub-district'] = c[0]

In [96]:
summary[summary['district'] == 'เมืองปาน']['sub-district'].value_counts()

sub-district
ทุ่งกว๋าว    32
แจ้ซ้อน      30
บ้านขอ       28
เมืองปาน     22
หัวเมือง     18
Name: count, dtype: int64

In [97]:
summary.loc[summary['province'] != "ลำปาง", "province"] = "ลำปาง"
summary['province'].unique()

<StringArray>
['ลำปาง']
Length: 1, dtype: str

In [106]:
anomaly_subdistrict = []
for district in all_distrcit:
    l = summary[summary['district'] == district]['sub-district'].value_counts().index.tolist()
    l_check = list(d[district].keys())
    for it in l:
        if it not in l_check:
            print(l_check)
            print(f"District: {district} have anomaly sub-district: {it}")
            anomaly_subdistrict.append(it)
    # if l != l_check:
    #     print(district)

['ทุ่งฮั้ว', 'วังเหนือ', 'วังใต้', 'ร่องเคาะ', 'วังทอง', 'วังซ้าย', 'วังแก้ว', 'วังทรายคำ']
District: วังเหนือ have anomaly sub-district: บ้านใหม่

In [107]:
summary[summary['sub-district'].isin(anomaly_subdistrict)]

,type,province,district,sub-district,unit_number,total_ballots,valid_ballots,invalid_ballots,no_vote_ballots,remain_ballots
218,เขต,ลำปาง,วังเหนือ,บ้านใหม่,1,460,297,34,12,117
219,เขต,ลำปาง,วังเหนือ,บ้านใหม่,2,420,293,21,14,-1
220,เขต,ลำปาง,วังเหนือ,บ้านใหม่,3,540,333,16,21,160
221,เขต,ลำปาง,วังเหนือ,บ้านใหม่,4,560,400,70,17,160
295,บช,ลำปาง,วังเหนือ,บ้านใหม่,1,540,350,17,13,160
296,บช,ลำปาง,วังเหนือ,บ้านใหม่,2,420,328,20,9,-1
297,บช,ลำปาง,วังเหนือ,บ้านใหม่,3,460,315,21,7,-1
298,บช,ลำปาง,วังเหนือ,บ้านใหม่,4,560,378,32,12,160

In [116]:
wang_north = summary[summary['district'] == 'วังเหนือ']['sub-district'].unique()
print(wang_north)
print(d['วังเหนือ'])
summary[(summary['district'] == 'วังเหนือ') & (summary['sub-district'] == 'วังเหนือ')]
# for sub_dis, val in d['วังเหนือ'].items():
#     if

<StringArray>
[   'วังใต้',  'ทุ่งฮั้ว',  'บ้านใหม่',  'ร่องเคาะ',   'วังซ้าย', 'วังทรายคำ',
    'วังทอง',  'วังเหนือ',   'วังแก้ว']
Length: 9, dtype: str
{'ทุ่งฮั้ว': 12, 'วังเหนือ': 12, 'วังใต้': 7, 'ร่องเคาะ': 18, 'วังทอง': 9, 'วังซ้าย': 10, 'วังแก้ว': 7, 'วังทรายคำ': 9}

,type,province,district,sub-district,unit_number,total_ballots,valid_ballots,invalid_ballots,no_vote_ballots,remain_ballots
268,เขต,ลำปาง,วังเหนือ,วังเหนือ,1,200,134,8,50,50
269,เขต,ลำปาง,วังเหนือ,วังเหนือ,2,240,163,13,9,55
270,เขต,ลำปาง,วังเหนือ,วังเหนือ,3,780,463,24,52,461
271,เขต,ลำปาง,วังเหนือ,วังเหนือ,4,600,429,41,42,771
272,เขต,ลำปาง,วังเหนือ,วังเหนือ,5,360,216,17,29,98
273,เขต,ลำปาง,วังเหนือ,วังเหนือ,6,420,280,34,7,99
274,เขต,ลำปาง,วังเหนือ,วังเหนือ,7,100,125,15,18,44
275,เขต,ลำปาง,วังเหนือ,วังเหนือ,8,440,298,18,27,97
345,บช,ลำปาง,วังเหนือ,วังเหนือ,1,200,137,13,-1,50
346,บช,ลำปาง,วังเหนือ,วังเหนือ,2,240,185,23,7,55
347,บช,ลำปาง,วังเหนือ,วังเหนือ,3,720,539,34,29,181
348,บช,ลำปาง,วังเหนือ,วังเหนือ,4,600,429,31,26,11
349,บช,ลำปาง,วังเหนือ,วังเหนือ,5,360,262,20,30,98
350,บช,ลำปาง,วังเหนือ,วังเหนือ,6,420,321,30,9,99
351,บช,ลำปาง,วังเหนือ,วังเหนือ,7,200,150,13,13,24
352,บช,ลำปาง,วังเหนือ,วังเหนือ,8,440,303,20,20,97

In [120]:
with open('../election-stations-2569.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
s = set()
for p in data['provinces']:
    if p['name'] == "ลำปาง":
        for a in p['areas']:
            if a['area'] == 2:
                for unit in a['stations']:
                    if unit['district'] == 'วังเหนือ':
                        print(unit)

{'code': '52-02-520701-001', 'name': 'อาคารศาลาประชาคมหมู่บ้านบ้านทุ่งปี้ หมู่ที่ 1', 'district': 'วังเหนือ', 'subdistrict': 'ทุ่งฮั้ว'}
{'code': '52-02-520701-002', 'name': 'อาคารอเนกประสงค์วัดแม่ทรายเงิน หมู่ที่ 2', 'district': 'วังเหนือ', 'subdistrict': 'ทุ่งฮั้ว'}
{'code': '52-02-520701-003', 'name': 'อาคารอเนกประสงค์บ้านผาดิน หมู่ที่ 3', 'district': 'วังเหนือ', 'subdistrict': 'ทุ่งฮั้ว'}
{'code': '52-02-520701-004', 'name': 'อาคารอเนกประสงค์บ้านทุ่งฮั้ว หมู่ที่ 4', 'district': 'วังเหนือ', 'subdistrict': 'ทุ่งฮั้ว'}
{'code': '52-02-520701-005', 'name': 'โรงเรียนบ้านวังมน หมู่ที่ 5', 'district': 'วังเหนือ', 'subdistrict': 'ทุ่งฮั้ว'}
{'code': '52-02-520701-006', 'name': 'อาคารอเนกประสงค์บ้านผาแดง หมู่ที่ 6', 'district': 'วังเหนือ', 'subdistrict': 'ทุ่งฮั้ว'}
{'code': '52-02-520701-007', 'name': 'ศาลาการเปรียญวัดห้วยกันทา หมู่ที่ 7', 'district': 'วังเหนือ', 'subdistrict': 'ทุ่งฮั้ว'}
{'code': '52-02-520701-008', 'name': 'อาคารอเนกประสงค์บ้านแม่เลียบ หมู่ที่ 8', 'district': 'วังเหนือ', 'subdistrict': 'ทุ่งฮั้ว'}
{'code': '52-02-520701-009', 'name': 'อาคารอเนกประสงค์บ้านบนทุ่ง หมู่ที่ 9', 'district': 'วังเหนือ', 'subdistrict': 'ทุ่งฮั้ว'}
{'code': '52-02-520701-010', 'name': 'อาคารอเนกประสงค์บ้านป่าบง -ฮ่องไฮ หมู่ที่10', 'district': 'วังเหนือ', 'subdistrict': 'ทุ่งฮั้ว'}
{'code': '52-02-520701-011', 'name': 'อาคารอเนกประสงค์บ้านทุ่งฮั้วพัฒนา หมู่ที่ 11', 'district': 'วังเหนือ', 'subdistrict': 'ทุ่งฮั้ว'}
{'code': '52-02-520701-012', 'name': 'อาคารอเนกประสงค์บ้านทุ่งวังทอง หมู่ที่ 12', 'district': 'วังเหนือ', 'subdistrict': 'ทุ่งฮั้ว'}
{'code': '52-02-520702T1-001', 'name': 'อาคารชมรมผู้สูงอายุบ้านทัพป่าเส้า หมู่ที่ 1 บ้านทัพป่าเส้า', 'district': 'วังเหนือ', 'subdistrict': 'วังเหนือ'}
{'code': '52-02-520702T1-002', 'name': 'อาคารอเนกประสงค์บ้านใหม่พัฒนา หมู่ที่ 2 บ้านใหม่พัฒนา', 'district': 'วังเหนือ', 'subdistrict': 'วังเหนือ'}
{'code': '52-02-520702T1-003', 'name': 'หอประชุมโรงเรียนชุมชนบ้านใหม่  หมู่ที่ 6 บ้านใหม่', 'district': 'วังเหนือ', 'subdistrict': 'วังเหนือ'}
{'code': '52-02-520702T1-004', 'name': 'อาคารรวมใจผู้สูงอายุบ้านใหม่ หมู่ที่ 6 บ้านใหม่', 'district': 'วังเหนือ', 'subdistrict': 'วังเหนือ'}
{'code': '52-02-520702T2-001', 'name': 'อาคารอเนกประสงค์บ้านห้วยเกี๋ยง หมู่ 1', 'district': 'วังเหนือ', 'subdistrict': 'วังเหนือ'}
{'code': '52-02-520702T2-002', 'name': 'อาคารอเนกประสงค์บ้านห้วยข่อย หมู่ 3', 'district': 'วังเหนือ', 'subdistrict': 'วังเหนือ'}
{'code': '52-02-520702T2-003', 'name': 'ศาลาการเปรียญวัดทุ่งเป้า หมู่ 4', 'district': 'วังเหนือ', 'subdistrict': 'วังเหนือ'}
{'code': '52-02-520702T2-004', 'name': 'โรงเรียนผู้สูงอายุเทศบาลตำบลวังเหนือ หมู่ 4', 'district': 'วังเหนือ', 'subdistrict': 'วังเหนือ'}
{'code': '52-02-520702T2-005', 'name': 'อาคารอเนกประสงค์บ้านแพะใต้ หมู่ 5', 'district': 'วังเหนือ', 'subdistrict': 'วังเหนือ'}
{'code': '52-02-520702T2-006', 'name': 'อาคารอเนกประสงค์บ้านแม่เฮียว หมู่ 7', 'district': 'วังเหนือ', 'subdistrict': 'วังเหนือ'}
{'code': '52-02-520702T2-007', 'name': 'อาคารอเนกประสงค์บ้านป่าเหียง หมู่ 8', 'district': 'วังเหนือ', 'subdistrict': 'วังเหนือ'}
{'code': '52-02-520702T2-008', 'name': 'ศาลาการเปรียญวัดขันหอม บ้านขันหอม หมู่ 9', 'district': 'วังเหนือ', 'subdistrict': 'วังเหนือ'}
{'code': '52-02-520703-001', 'name': 'ศาลาการเปรียญวัดบ้านกวาง หมู่ที่ 1', 'district': 'วังเหนือ', 'subdistrict': 'วังใต้'}
{'code': '52-02-520703-002', 'name': 'อาคารอเนกประสงค์บ้านวังโป่ง หมู่ที่ 2', 'district': 'วังเหนือ', 'subdistrict': 'วังใต้'}
{'code': '52-02-520703-003', 'name': 'อาคารอเนกประสงค์บ้านไผ่กลาง หมู่ที่ 3', 'district': 'วังเหนือ', 'subdistrict': 'วังใต้'}
{'code': '52-02-520703-004', 'name': 'อาคารอเนกประสงค์บ้านแม่โป่ง หมู่ที่ 4', 'district': 'วังเหนือ', 'subdistrict': 'วังใต้'}
{'code': '52-02-520703-005', 'name': 'โรงเรียนบ้านแม่พริก หมู่ที่ 5', 'district': 'วังเหนือ', 'subdistrict': 'วังใต้'}
{'code': '52-02-520703-006', 'name': 'อาคารอเนกประสงค์บ้านหมุ้น หมู่ที่ 6', 'district': 'วังเหนือ', 'subdistrict': 'วังใต้'}
{'code': '52-02-520703-007', 'name': 'อาคารอเนกประสงค์บ้านโปร่งเจริญ หมู่ที่ 7', 'district': 'วังเหนือ', 'subdistrict': 'วังใต้'}
{'code': '52-02-520704-001', 'name': 'อาคารอเนกประสงค์บ้านผาช่อ หมู่ที่ 1', 'district': 'วังเหนือ', 'subdistrict': 'ร่องเคาะ'}
{'code': '52-02-520704-002', 'name': 'อาคารอเนกประสงค์บ้านห้วยก้อด หมู่ที่ 2', 'district': 'วังเหนือ', 'subdistrict': 'ร่องเคาะ'}
{'code': '52-02-520704-003', 'name': 'โรงเรียนบ้านป่าคา หมู่ที่ 3', 'district': 'วังเหนือ', 'subdistrict': 'ร่องเคาะ'}
{'code': '52-02-520704-004', 'name': 'ศาลาการเปรียญวัดทุ่งฝูง หมู่ที่ 4', 'district': 'วังเหนือ', 'subdistrict': 'ร่องเคาะ'}
{'code': '52-02-520704-005', 'name': 'อาคารอเนกประสงค์บ้านแม่ลืน หมู่ที่ 5', 'district': 'วังเหนือ', 'subdistrict': 'ร่องเคาะ'}
{'code': '52-02-520704-006', 'name': 'อาคารอเนกประสงค์บ้านแม่สงเหนือ หมู่ที่ 6', 'district': 'วังเหนือ', 'subdistrict': 'ร่องเคาะ'}
{'code': '52-02-520704-007', 'name': 'ศาลาการเปรียญวัดสบลืน หมู่ที่ 7', 'district': 'วังเหนือ', 'subdistrict': 'ร่องเคาะ'}
{'code': '52-02-520704-008', 'name': 'อาคารอเนกประสงค์บ้านดอนแก้ว หมู่ที่ 8', 'district': 'วังเหนือ', 'subdistrict': 'ร่องเคาะ'}
{'code': '52-02-520704-009', 'name': 'อาคารอเนกประสงค์บ้านร่องเคาะ หมู่ที่ 9', 'district': 'วังเหนือ', 'subdistrict': 'ร่องเคาะ'}
{'code': '52-02-520704-010', 'name': 'ศาลาการเปรียญวัดแม่สงใต้ หมู่ที่ 10', 'district': 'วังเหนือ', 'subdistrict': 'ร่องเคาะ'}
{'code': '52-02-520704-011', 'name': 'อาคารอเนกประสงค์บ้านแสนตอ หมู่ที่ 11', 'district': 'วังเหนือ', 'subdistrict': 'ร่องเคาะ'}
{'code': '52-02-520704-012', 'name': 'หอประชุมประจำหมู่บ้านบ้านวังใหม่ หมู่ที่ 12', 'district': 'วังเหนือ', 'subdistrict': 'ร่องเคาะ'}
{'code': '52-02-520704-013', 'name': 'หอประชุมหมู่บ้าน (หลังใหม่) บ้านวังใหม่ หมู่ที่ 12', 'district': 'วังเหนือ', 'subdistrict': 'ร่องเคาะ'}
{'code': '52-02-520704-014', 'name': 'อาคารกองทุนหมู่บ้านบ้านทุ่งตุ้น หมู่ที่ 13', 'district': 'วังเหนือ', 'subdistrict': 'ร่องเคาะ'}
{'code': '52-02-520704-015', 'name': 'อาคารอเนกประสงค์บ้านห้วยน้ำ หมู่ที่ 14', 'district': 'วังเหนือ', 'subdistrict': 'ร่องเคาะ'}
{'code': '52-02-520704-016', 'name': 'อาคารศูนย์ฝึกอาชีพสตรีบ้านจำตอง หมู่ที่ 15', 'district': 'วังเหนือ', 'subdistrict': 'ร่องเคาะ'}
{'code': '52-02-520704-017', 'name': 'อาคารอเนกประสงค์บ้านต้นผึ้ง หมู่ที่ 16', 'district': 'วังเหนือ', 'subdistrict': 'ร่องเคาะ'}
{'code': '52-02-520704-018', 'name': 'อาคารอเนกประสงค์บ้านวังนิตร หมู่ที่ 17', 'district': 'วังเหนือ', 'subdistrict': 'ร่องเคาะ'}
{'code': '52-02-520705-001', 'name': 'อาคารอเนกประสงค์บ้านตึงใต้ หมู่ที่ 1', 'district': 'วังเหนือ', 'subdistrict': 'วังทอง'}
{'code': '52-02-520705-002', 'name': 'โรงเรียนวังทองวิทยา หมู่ที่ 2', 'district': 'วังเหนือ', 'subdistrict': 'วังทอง'}
{'code': '52-02-520705-003', 'name': 'ศาลาการเปรียญวัดปงถ้ำ หมู่ที่ 3', 'district': 'วังเหนือ', 'subdistrict': 'วังทอง'}
{'code': '52-02-520705-004', 'name': 'อาคารอเนกประสงค์บ้านแม่เย็น หมู่ที่ 4', 'district': 'วังเหนือ', 'subdistrict': 'วังทอง'}
{'code': '52-02-520705-005', 'name': 'อาคารอเนกประสงค์บ้านป่าลัน หมู่ที่ 5', 'district': 'วังเหนือ', 'subdistrict': 'วังทอง'}
{'code': '52-02-520705-006', 'name': 'อาคารอเนกประสงค์บ้านสารภี หมู่ที่ 6', 'district': 'วังเหนือ', 'subdistrict': 'วังทอง'}
{'code': '52-02-520705-007', 'name': 'เต้นท์ชั่วคราวที่ทำการองค์การบริหารส่วนตำบลวังทอง หมู่ที่ 7', 'district': 'วังเหนือ', 'subdistrict': 'วังทอง'}
{'code': '52-02-520705-008', 'name': 'อาคารอเนกประสงค์บ้านเมืองทอง หมู่ที่ 8', 'district': 'วังเหนือ', 'subdistrict': 'วังทอง'}
{'code': '52-02-520705-009', 'name': 'อาคารอเนกประสงค์บ้านร่มโพธิ์ทอง หมู่ที่ 9', 'district': 'วังเหนือ', 'subdistrict': 'วังทอง'}
{'code': '52-02-520706-001', 'name': 'อาคารอเนกประสงค์บ้านแม่ม่า หมู่ที่ 1', 'district': 'วังเหนือ', 'subdistrict': 'วังซ้าย'}
{'code': '52-02-520706-002', 'name': 'อาคารอเนกประสงค์บ้านใหม่หล่ายท่า หมู่ที่ 2', 'district': 'วังเหนือ', 'subdistrict': 'วังซ้าย'}
{'code': '52-02-520706-003', 'name': 'อาคารอเนกประสงค์บ้านหัวทุ่ง หมู่ที่ 3', 'district': 'วังเหนือ', 'subdistrict': 'วังซ้าย'}
{'code': '52-02-520706-004', 'name': 'อาคารอเนกประสงค์บ้านแม่สุกใน หมู่ที่ 4', 'district': 'วังเหนือ', 'subdistrict': 'วังซ้าย'}
{'code': '52-02-520706-005', 'name': 'อาคารอเนกประสงค์บ้านป่าแขม หมู่ที่ 5', 'district': 'วังเหนือ', 'subdistrict': 'วังซ้าย'}
{'code': '52-02-520706-006', 'name': 'อาคารอเนกประสงค์บ้านน้ำหลง หมู่ที่ 6', 'district': 'วังเหนือ', 'subdistrict': 'วังซ้าย'}
{'code': '52-02-520706-007', 'name': 'อาคารอเนกประสงค์บ้านแม่สุขวังเหนือ  หมู่ที่ 7', 'district': 'วังเหนือ', 'subdistrict': 'วังซ้าย'}
{'code': '52-02-520706-008', 'name': 'อาคารอเนกประสงค์บ้านแม่สุขวังเหนือ หมู่ที่ 8', 'district': 'วังเหนือ', 'subdistrict': 'วังซ้าย'}
{'code': '52-02-520706-009', 'name': 'อาคารที่ทำการกองทุนหมู่บ้าน บ้านแม่สุขป่าสัก หมู่ที่ 9', 'district': 'วังเหนือ', 'subdistrict': 'วังซ้าย'}
{'code': '52-02-520706-010', 'name': 'อาคารอเนกประสงค์บ้านสบม่า หมู่ที่ 10', 'district': 'วังเหนือ', 'subdistrict': 'วังซ้าย'}
{'code': '52-02-520707-001', 'name': 'ศาลาประชาคมหน้าวัดแม่หีด หมู่ที่ 1', 'district': 'วังเหนือ', 'subdistrict': 'วังแก้ว'}
{'code': '52-02-520707-002', 'name': 'ศาลาการเปรียญวัดบ้านฮ่าง หมู่ที่ 2', 'district': 'วังเหนือ', 'subdistrict': 'วังแก้ว'}
{'code': '52-02-520707-003', 'name': 'อาคาร SML บ้านป่าแหน่ง หมู่ที่ 3', 'district': 'วังเหนือ', 'subdistrict': 'วังแก้ว'}
{'code': '52-02-520707-004', 'name': 'ศาลาการเปรียญวัดค่ายวัง หมู่ที่ 4', 'district': 'วังเหนือ', 'subdistrict': 'วังแก้ว'}
{'code': '52-02-520707-005', 'name': 'อาคารอเนกประสงค์บ้านฮ่างวังแก้ว หมู่ที่ 5', 'district': 'วังเหนือ', 'subdistrict': 'วังแก้ว'}
{'code': '52-02-520707-006', 'name': 'อาคารกองทุนหมู่บ้านห้วยป้าย หมู่ที่ 6', 'district': 'วังเหนือ', 'subdistrict': 'วังแก้ว'}
{'code': '52-02-520707-007', 'name': 'อาคารอเนกประสงค์ประจำหมู่บ้าน หมู่ที่ 7', 'district': 'วังเหนือ', 'subdistrict': 'วังแก้ว'}
{'code': '52-02-520708-001', 'name': 'อาคารอเนกประสงค์บ้านทุ่งฮี หมู่ที่ 1', 'district': 'วังเหนือ', 'subdistrict': 'วังทรายคำ'}
{'code': '52-02-520708-002', 'name': 'อาคารอเนกประสงค์บ้านดง หมู่ที่ 2', 'district': 'วังเหนือ', 'subdistrict': 'วังทรายคำ'}
{'code': '52-02-520708-003', 'name': 'อาคารอเนกประสงค์บ้านปงวัง หมู่ที่ 3', 'district': 'วังเหนือ', 'subdistrict': 'วังทรายคำ'}
{'code': '52-02-520708-004', 'name': 'อาคารอเนกประสงค์บ้านต้นฮ่าง หมู่ที่ 4', 'district': 'วังเหนือ', 'subdistrict': 'วังทรายคำ'}
{'code': '52-02-520708-005', 'name': 'อาคารอเนกประสงค์บ้านป่าฝาง หมู่ที่ 5', 'district': 'วังเหนือ', 'subdistrict': 'วังทรายคำ'}
{'code': '52-02-520708-006', 'name': 'โรงเรียนบ้านก่อ หมู่ที่ 6', 'district': 'วังเหนือ', 'subdistrict': 'วังทรายคำ'}
{'code': '52-02-520708-007', 'name': 'อาคารอเนกประสงค์บ้านป่าสัก หมู่ที่ 7', 'district': 'วังเหนือ', 'subdistrict': 'วังทรายคำ'}
{'code': '52-02-520708-008', 'name': 'ศาลาการเปรียญวัดทุ่งห้า หมู่ที่ 8', 'district': 'วังเหนือ', 'subdistrict': 'วังทรายคำ'}
{'code': '52-02-520708-009', 'name': 'อาคารอเนกประสงค์บ้านทุ่งพัฒนา หมู่ที่ 9', 'district': 'วังเหนือ', 'subdistrict': 'วังทรายคำ'}

In [129]:
# แปลกตรงที่ jsn election station ไม่มีตำบลบ้ายใหม่ แต่ใน pdf มี บ้านใหม่แล้วก็ วังเหนือมีแต่ 8 แต่น json มี 12 หน่วย
check = summary[summary['district'] == 'งาว'].groupby('sub-district')['unit_number'].count()
miss_subdistrict = []
for key, val in d['งาว'].items():
    if check[key]/2 != val:
        print(f"ตำบล: {key}, target: {val}, but have only: {check[key]/2}")
        miss_subdistrict.append(key)

ตำบล: หลวงใต้, target: 8, but have only: 7.5
ตำบล: นาแก, target: 6, but have only: 5.0
ตำบล: บ้านอ้อน, target: 8, but have only: 7.5